# Generated by Django 2.2.14 on 2020-11-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar_promotions', '0011_auto_20200810_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cta_text',
            field=models.TextField(blank=True, help_text='Call to action text', verbose_name='CTA Text'),
        ),
    ]
