# Generated by Django 2.2.14 on 2020-12-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar_promotions', '0012_image_cta_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='cta_text',
            field=models.CharField(blank=True, help_text='Call to action text', max_length=255, verbose_name='CTA Text'),
        ),
    ]
