# Generated by Django 2.2.14 on 2020-12-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar_promotions', '0013_auto_20201202_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='cta_text',
            field=models.CharField(help_text='Call to action button text', max_length=255, verbose_name='CTA Text'),
        ),
    ]
